apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-swarm-visualizer
spec:
  selector:
    matchLabels:
      app: docker-swarm-visualizer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: docker-swarm-visualizer
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: docker-swarm
    spec:
      automountServiceAccountToken: false
      containers:
      - name: docker-swarm-visualizer
        image: pushpendrasingh3tcscom/docker-swarm:8948279-29
