---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: pushpendras21/my-app:1.5.4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-apache
  namespace: my-app
  labels:
    app: apache
spec:
  type: NodePort      
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
