---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: pushpendras21/my-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: my-app
  labels:
    app: nginx
spec:
  type: LoadBalancer      
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
