---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:pushpendrasingh3/argocd-setup.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCz/GLt+NgXUbZvyRNJ//KxriYK7plPQnpNj1eLz8uT4QAAAKhhcVXnYXFV
    5wAAAAtzc2gtZWQyNTUxOQAAACCz/GLt+NgXUbZvyRNJ//KxriYK7plPQnpNj1eLz8uT4Q
    AAAEAXU6fDtRVCz2EGbBJRi2eN8PuEKG570qLfPUAfkw5DL7P8Yu342BdRtm/JE0n/8rGu
    JgrumU9Cek2PV4vPy5PhAAAAHnB1c2hwZW5kcmFfc2luZ2gzQGJhc3Rpb24taG9zdAECAw
    QFBgc=
    -----END OPENSSH PRIVATE KEY-----      
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

