---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ravindrasinghh/argocd-setup.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD4VvJSOgw0f1q3ciDnuo1vLSENQp2+Pbi119YN01MymQAAAKD8mE3u/JhN
    7gAAAAtzc2gtZWQyNTUxOQAAACD4VvJSOgw0f1q3ciDnuo1vLSENQp2+Pbi119YN01MymQ
    AAAEATgwm3oJL8RAAni1KsHL/QAkc6HrQydJl+XCKNTyOG7/hW8lI6DDR/WrdyIOe6jW**
    *****************************
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

