name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_TAG: 1.4.2
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get latest tag
        #id: latest-tag
        run: |
          echo "GIT_TAG=`cat version`" >> "$GITHUB_ENV"
          echo "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> "$GITHUB_ENV"      
          docker build -t ${DOCKER_USER}/my-app:${GIT_TAG} -f argocd-cicd-setup/Dockerfile .
          docker push ${DOCKER_USER}/my-app:${GIT_TAG}
      - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          repository: pushpendrasingh3/argocd-setup
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
