name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_VERSION: "1.0.10"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USER}/my-app:${DOCKER_VERSION} -f argocd-cicd-setup/Dockerfile .
          docker push ${DOCKER_USER}/my-app:latest
      - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          #repository: ravindrasinghh/argocd-setup
          repository: pushpendrasingh3/argocd-setup
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
