name: main
on:
  workflow_dispatch:

env:
  INPUT_SECRET: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_TOKEN }}
          approvers: pushpendras21,pushpendrasingh3
      - name: Deploy to production
        run: echo deploying
